"use client";

import { useAgentProfile } from "@/components/AgentProfileProvider";
import type { Listing } from "@/lib/mock/listings";

const C = {
  base: "#316878",
  dark: "#1C3C45",
  light: "#50AAC4",
  body: "#555555",
  muted: "#8a8a8a",
};

// Branded, printable open house welcome sign with a working QR code that
// points to the agent's public page (visitors scan to connect / sign in).
// The QR is generated by a keyless public endpoint; in production swap for a
// self-hosted generator. Hidden on screen, printed alone (#print-area).
export default function OpenHouseSign({ listing }: { listing: Listing }) {
  const { profile } = useAgentProfile();
  const target = "https://agent-pages-topaz.vercel.app/p/jordan-sample";
  const qr = `https://api.qrserver.com/v1/create-qr-code/?size=420x420&color=1C3C45&data=${encodeURIComponent(target)}`;

  return (
    <div
      id="print-area"
      className="print-sheet"
      style={{
        color: C.dark,
        fontFamily: "var(--font-open-sans), sans-serif",
        textAlign: "center",
      }}
    >
      {/* Header band */}
      <div
        style={{
          background: C.base,
          color: "#fff",
          borderRadius: 14,
          padding: "26px 26px 22px",
        }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/logos/white-logo.svg"
          alt="Marshall Reddick Real Estate"
          width={240}
          style={{ margin: "0 auto" }}
        />
        <p
          style={{
            margin: "18px 0 0",
            fontSize: 44,
            fontWeight: 700,
            fontFamily: "var(--font-raleway), sans-serif",
            letterSpacing: 1,
          }}
        >
          Welcome Home
        </p>
        <p style={{ margin: "6px 0 0", fontSize: 15, letterSpacing: 4, color: "rgba(255,255,255,0.85)" }}>
          OPEN HOUSE
        </p>
      </div>

      {/* Property */}
      <p style={{ margin: "26px 0 0", fontSize: 26, fontWeight: 700, fontFamily: "var(--font-raleway), sans-serif" }}>
        {listing.address}
      </p>
      <p style={{ margin: "4px 0 0", fontSize: 15, color: C.body }}>
        {listing.city} · {listing.beds} bd · {listing.baths} ba · {listing.sqft} sqft · {listing.price}
      </p>

      {/* QR */}
      <div
        style={{
          margin: "26px auto 0",
          width: 240,
          padding: 16,
          border: `3px solid ${C.light}`,
          borderRadius: 18,
        }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={qr} alt="Scan to connect" width={208} height={208} style={{ display: "block" }} />
      </div>
      <p style={{ margin: "12px 0 0", fontSize: 16, fontWeight: 700, color: C.base }}>
        Scan to sign in and get the full property details
      </p>

      {/* Agent */}
      <div style={{ marginTop: 30, paddingTop: 16, borderTop: `2px solid ${C.base}` }}>
        <p style={{ margin: 0, fontSize: 18, fontWeight: 700 }}>
          Hosted by {profile.name}
        </p>
        <p style={{ margin: "2px 0 0", fontSize: 13, color: C.body }}>
          {profile.brokerage} · {profile.phone} · {profile.license}
        </p>
        <p style={{ margin: "10px 0 0", fontSize: 10, color: C.muted }}>
          Equal Housing Opportunity. Sample sign for reference design.
        </p>
      </div>
    </div>
  );
}
